### YamlMime:Sample
sample:
- name: Application resources and localization sample
  description: Shows how to use application resources to separate localizable content from app code.
  generateZip: true
  extendedZipContent:
  - path: /SharedContent
    target: /SharedContent
  preserveParentHierarchy: true
  author: oldnewthing
  languages:
  - csharp
  - cpp
  - js
  - vb
  technologies:
  - windows
  vssolution: /Samples/ApplicationResources/cs/ApplicationResources.sln
