### YamlMime:Sample
sample:
- name: Logging sample
  description: Shows how to use the Logging APIs in the Windows.Foundation.Diagnostics namespace, including LoggingChannel, LoggingActivity, LoggingSession, and FileLoggingSession.
  generateZip: true
  extendedZipContent:
  - path: /SharedContent
    target: /SharedContent
  preserveParentHierarchy: true
  author: oldnewthing
  languages:
  - csharp
  - cpp
  - js
  technologies:
  - windows
  vssolution: /Samples/Logging/cs/Logging.sln
